name = "medium-backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmUzMTVkYzktYTM5ZC00ZGMwLThiNTQtYTUyZDQ2NDE5NTQ5IiwidGVuYW50X2lkIjoiNzY0MDE0MTEyMDhlNWQ5NzQwZjc2MWI5YTcyZmM3NTRmNTRjYWNjZGI2Yjc4OWJiYzBjNjdhZmY4Y2M4Y2E5MiIsImludGVybmFsX3NlY3JldCI6Ijc4Yjk3ZGVhLTlhZWEtNGNkMi1iZmU3LTliMTY1NzM0MDE4NCJ9.riXIgEVw5lGWwbs0ZZak3o3iT_cOWjlYTcg_ahWsOWM"

JWT_SECRET="kajHJHKAJkjakljfk3i4uioum3bn4j"
